
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efbxsdoyzfwscdlwsiuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmYnhzZG95emZ3c2NkbHdzaXVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NTAwNDcsImV4cCI6MjA1NjIyNjA0N30.TypsI-POkPjsBERykNBI57FSONZ4uZwWOdLSqTWsQjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
